### ISSUE TITLE
BME280 support

### ISSUE THREAD

**Issue by 877dev** [Tobi0892/octoprint-mqtt-enclosure#2]
Hi,

I'd love to get this working with my Pi3B and BME280 sensor (i2c), so I can publish to my MQTT broker.
Could you advise if that's possible?

Thanks

**Comment by Tobi0892** [comment]
@877dev Sure, you could follow this Adafruit tutorial to get the BME280 working: 

https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/python-circuitpython-test#python-computer-wiring-2994989-5

I would advise to create a new BME280.py class similar to DHT22.py.
